### ISSUE TITLE
Statistik di Dashboard

### ISSUE THREAD

**Issue by syauqiahmd** [syauqiahmd/project_e-commerce#6]
- [ ] jumlah pengguna (public)
- [ ] Penjualan online yang belum selesai
- [ ] barang terjuall
- [ ] Total penjualan

**Comment by FaruqRahmadani** [comment]
olah akan tampilannya kena lak

**Comment by syauqiahmd** [comment]
wokeh.... aman ini hndak meolah nah

**Comment by FaruqRahmadani** [comment]
wuanjay wkwk gesit :v
